# Generated by Django 5.1.5 on 2025-02-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('lastname', models.CharField(max_length=100, verbose_name='lastname')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
        ),
    ]
